development:
  adapter: postgresql
  database: kill-all-sudoku/development
  username: Ka
  password: superbowl
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: UTF8
  database: kill-all-sudoku/test
  username: Ka
  password: superbowl
  pool: 5
  timeout: 5000